@extends('layouts.app')

@section('content')
<div class="max-w-4xl mx-auto">
    <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="p-6 bg-white border-b border-gray-200">
            <div class="flex flex-row w-full justify-between items-center space-x-3 mb-6">
                <a href="{{ route('products.index') }}" class="text-blue-600 hover:text-blue-800">← Back </a>
                <div class="flex items-center space-x-3">
                    <a href="{{ route('products.edit', $product) }}" 
                       class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700">
                        <svg class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                        </svg>
                        Edit 
                    </a>
                    <button onclick="deleteProduct()" 
                            class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700">
                        <svg class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                        Delete
                    </button>
                    <!-- <a href="{{ route('products.index') }}" class="text-blue-600 hover:text-blue-800">← Back to Products</a> -->
                </div>
            </div>
            <div class="flex items-center justify-between mb-6">
                <h2 class="text-2xl font-bold text-gray-900">Product Details</h2>
            </div>

            <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <div>
                    @if($product->image_url)
                        <img src="{{ $product->image_url }}" alt="{{ $product->name }}" 
                             class="w-full h-96 object-cover rounded-lg shadow-lg">
                    @else
                        <div class="w-full h-96 bg-gray-200 rounded-lg shadow-lg flex items-center justify-center">
                            <span class="text-gray-500 text-lg">No Image Available</span>
                        </div>
                    @endif
                </div>

                <div class="space-y-6">
                    <div>
                        <h3 class="text-lg font-medium text-gray-900">Product Name</h3>
                        <p class="mt-1 text-xl text-gray-900">{{ $product->name }}</p>
                    </div>

                    <div>
                        <h3 class="text-lg font-medium text-gray-900">Description</h3>
                        <p class="mt-1 text-gray-700">{{ $product->description }}</p>
                        @if($product->is_ai_generated_description)
                            <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-800 mt-2">
                                AI Generated
                            </span>
                        @endif
                    </div>

                    <div>
                        <h3 class="text-lg font-medium text-gray-900">Upload Method</h3>
                        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium 
                            {{ $product->upload_method === 'manual' ? 'bg-blue-100 text-blue-800' : 'bg-green-100 text-green-800' }}">
                            {{ ucfirst($product->upload_method) }}
                        </span>
                    </div>

                    <div>
                        <h3 class="text-lg font-medium text-gray-900">AI Generation Status</h3>
                        <div class="mt-2 space-y-2">
                            @if($product->is_ai_generated_description)
                                <div class="flex items-center">
                                    <svg class="h-5 w-5 text-green-500 mr-2" fill="currentColor" viewBox="0 0 20 20">
                                        <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                                    </svg>
                                    <span class="text-sm text-gray-700">Description generated by AI</span>
                                </div>
                            @endif
                            @if($product->is_ai_generated_image)
                                <div class="flex items-center">
                                    <svg class="h-5 w-5 text-green-500 mr-2" fill="currentColor" viewBox="0 0 20 20">
                                        <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                                    </svg>
                                    <span class="text-sm text-gray-700">Image generated by AI</span>
                                </div>
                            @endif
                        </div>
                    </div>

                    <div>
                        <h3 class="text-lg font-medium text-gray-900">Storage Information</h3>
                        <div class="mt-2 space-y-1 text-sm text-gray-600">
                            @if($product->image_path)
                                <p><strong>Image Path:</strong> {{ $product->image_path }}</p>
                            @endif
                            @if($product->image_url)
                                <p><strong>Image URL:</strong> 
                                    <a href="{{ $product->image_url }}" target="_blank" class="text-blue-600 hover:text-blue-800">
                                        {{ $product->image_url }}
                                    </a>
                                </p>
                            @endif
                        </div>
                    </div>

                    <div>
                        <h3 class="text-lg font-medium text-gray-900">Timestamps</h3>
                        <div class="mt-2 space-y-1 text-sm text-gray-600">
                            <p><strong>Created:</strong> {{ $product->created_at->format('F d, Y \a\t g:i A') }}</p>
                            <p><strong>Updated:</strong> {{ $product->updated_at->format('F d, Y \a\t g:i A') }}</p>
                        </div>
                    </div>

                    @if($product->metadata)
                        <div>
                            <h3 class="text-lg font-medium text-gray-900">Additional Information</h3>
                            <div class="mt-2 p-3 bg-gray-50 rounded-md">
                                <pre class="text-xs text-gray-700">{{ json_encode($product->metadata, JSON_PRETTY_PRINT) }}</pre>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

@stack('scripts')
<script>
function deleteProduct() {
    if (confirm('Are you sure you want to delete this product? This action cannot be undone.')) {
        const deleteBtn = event.target;
        const originalText = deleteBtn.textContent;
        
        deleteBtn.textContent = 'Deleting...';
        deleteBtn.disabled = true;
        
        axios.delete('{{ route("products.destroy", $product) }}')
        .then(function (response) {
            if (response.data.success) {
                alert('Product deleted successfully!');
                window.location.href = '{{ route("products.index") }}';
            } else {
                alert('Error: ' + response.data.message);
            }
        })
        .catch(function (error) {
            let errorMessage = 'Failed to delete product';
            if (error.response && error.response.data) {
                errorMessage += ': ' + error.response.data.message;
            }
            alert(errorMessage);
        })
        .finally(function () {
            deleteBtn.textContent = originalText;
            deleteBtn.disabled = false;
        });
    }
}
</script>
@endsection
